namespace Zadana.Application.Modules.Identity.DTOs;

public record AdminCustomerListItemDto(
    Guid Id,
    string FullName,
    string? Email,
    string? Phone,
    string? City,
    string? Area,
    string AccountStatus,
    bool IsLoginLocked,
    bool EmailConfirmed,
    bool PhoneConfirmed,
    DateTime CreatedAtUtc,
    DateTime? LastLoginAtUtc,
    DateTime? LastSeenAtUtc,
    bool IsOnlineNow,
    int TotalOrders,
    decimal TotalSpent,
    decimal AverageBasket,
    DateTime? LastOrderAtUtc,
    decimal LastOrderValue,
    int RefundedOrdersCount,
    int FavoritesCount);

public record AdminCustomerRecentOrderDto(
    Guid Id,
    string OrderNumber,
    DateTime PlacedAtUtc,
    decimal TotalAmount,
    string Status,
    string PaymentStatus);

public record AdminCustomerDetailDto(
    Guid Id,
    string FullName,
    string? Email,
    string? Phone,
    string? ProfilePhotoUrl,
    string? City,
    string? Area,
    string? AddressLine,
    string? BuildingNo,
    string? FloorNo,
    string? ApartmentNo,
    string? AddressLabel,
    string AccountStatus,
    bool IsLoginLocked,
    bool EmailConfirmed,
    bool PhoneConfirmed,
    DateTime CreatedAtUtc,
    DateTime? LastLoginAtUtc,
    DateTime? LastSeenAtUtc,
    bool IsOnlineNow,
    int TotalOrders,
    decimal TotalSpent,
    decimal AverageBasket,
    DateTime? LastOrderAtUtc,
    decimal LastOrderValue,
    int RefundedOrdersCount,
    int FavoritesCount,
    IReadOnlyList<AdminCustomerRecentOrderDto> RecentOrders);
