# Generates SaudiGeographyCatalog.cs from scripts/saudi-geography-manifest.json
$ErrorActionPreference = 'Stop'
$root = Split-Path $PSScriptRoot -Parent
$manifestPath = Join-Path $PSScriptRoot 'saudi-geography-manifest.json'
$outPath = Join-Path $root 'src\Zadana.Infrastructure\Data\SaudiGeographyCatalog.cs'

$regionCenters = @{
    RIYADH = @(24.7136, 46.6753)
    MAKKAH = @(21.4225, 39.8262)
    MADINAH = @(24.4672, 39.6024)
    EASTERN = @(26.3927, 49.9777)
    QASSIM = @(26.3267, 43.9650)
    HAIL = @(27.5114, 41.7208)
    TABUK = @(28.3835, 36.5662)
    NORTHERN_BORDERS = @(30.9753, 41.0186)
    JAWF = @(29.9697, 40.2064)
    JIZAN = @(16.8893, 42.5510)
    ASIR = @(18.2164, 42.5053)
    BAHA = @(20.0000, 41.4667)
    NAJRAN = @(17.4933, 44.1322)
}

$doc = Get-Content $manifestPath -Raw -Encoding UTF8 | ConvertFrom-Json
$regionIdByCode = @{}
foreach ($r in $doc.regions) { $regionIdByCode[$r.code] = $r.id }

$cityLines = New-Object System.Collections.Generic.List[string]
$sortByRegion = @{}
$cityId = 200
foreach ($c in $doc.cities) {
    if (-not $sortByRegion.ContainsKey($c.region)) { $sortByRegion[$c.region] = 0 }
    $sortByRegion[$c.region]++
    $sort = $sortByRegion[$c.region]
    $lat = if ($c.PSObject.Properties.Name -contains 'lat') { $c.lat } else { $regionCenters[$c.region][0] }
    $lon = if ($c.PSObject.Properties.Name -contains 'lon') { $c.lon } else { $regionCenters[$c.region][1] }
    $cityId++
    $guid = ('20000000-0000-0000-0000-{0:D12}' -f $cityId)
    $regionId = $regionIdByCode[$c.region]
    $nameAr = ($c.nameAr -replace '\\','\\' -replace '"','\"')
    $nameEn = ($c.nameEn -replace '\\','\\' -replace '"','\"')
    $cityLines.Add("        new SaudiGeographyCitySeed(""$($c.code)"", ""$($c.region)"", ""$nameAr"", ""$nameEn"", $lat, $lon, 12, $sort, Guid.Parse(""$regionId"")),")
}

$regionLines = foreach ($r in $doc.regions) {
    $nameAr = ($r.nameAr -replace '\\','\\' -replace '"','\"')
    $nameEn = ($r.nameEn -replace '\\','\\' -replace '"','\"')
    "        new SaudiGeographyRegionSeed(""$($r.code)"", ""$nameAr"", ""$nameEn"", $($r.lat), $($r.lon), $($r.zoom), $($r.sort), Guid.Parse(""$($r.id)"")),"
}

$sb = @"
// <auto-generated> Run scripts/Generate-SaudiGeographyCatalog.ps1 to regenerate.</auto-generated>
namespace Zadana.Infrastructure.Data;

public static class SaudiGeographyCatalog
{
    public static IReadOnlyList<SaudiGeographyRegionSeed> Regions { get; } =
    [
$($regionLines -join "`n")
    ];

    public static IReadOnlyList<SaudiGeographyCitySeed> Cities { get; } =
    [
$($cityLines -join "`n")
    ];
}

public sealed record SaudiGeographyRegionSeed(
    string Code,
    string NameAr,
    string NameEn,
    double Latitude,
    double Longitude,
    int MapZoom,
    int SortOrder,
    Guid Id);

public sealed record SaudiGeographyCitySeed(
    string Code,
    string RegionCode,
    string NameAr,
    string NameEn,
    double Latitude,
    double Longitude,
    int MapZoom,
    int SortOrder,
    Guid RegionId);
"@

New-Item -ItemType Directory -Force -Path (Split-Path $outPath) | Out-Null
[System.IO.File]::WriteAllText($outPath, $sb, [System.Text.UTF8Encoding]::new($false))
Write-Host "Wrote $($doc.cities.Count) cities and $($doc.regions.Count) regions to $outPath"
