namespace Zadana.Application.Modules.Vendors.DTOs;

public record VendorWorkspaceDto(
    Guid Id,
    string BusinessNameAr,
    string BusinessNameEn,
    string BusinessType,
    string CommercialRegistrationNumber,
    DateTime? CommercialRegistrationExpiryDate,
    string? TaxId,
    string? LicenseNumber,
    string ContactEmail,
    string ContactPhone,
    string? DescriptionAr,
    string? DescriptionEn,
    string? Region,
    string? City,
    string? NationalAddress,
    string? OwnerName,
    string? OwnerEmail,
    string? OwnerPhone,
    string? IdNumber,
    string? Nationality,
    string? PayoutCycle,
    string FinancialLifecycleMode,
    decimal? CommissionRate,
    string Status,
    string AccountStatus,
    bool IsLoginLocked,
    DateTime? LockedAtUtc,
    DateTime? ArchivedAtUtc,
    DateTime? SuspendedAtUtc,
    string? RejectionReason,
    string? SuspensionReason,
    string? LockReason,
    string? ArchiveReason,
    string? LogoUrl,
    string? CommercialRegisterDocumentUrl,
    string? TaxDocumentUrl,
    string? LicenseDocumentUrl,
    DateTime? ApprovedAtUtc,
    string? ApprovedByName,
    DateTime CreatedAtUtc,
    DateTime UpdatedAtUtc,
    VendorOperationsSettingsDto OperationsSettings,
    VendorNotificationSettingsDto NotificationSettings,
    int BranchesCount,
    int BankAccountsCount,
    VendorBankAccountDto? PrimaryBankAccount,
    IReadOnlyList<VendorOperatingHourDto> OperatingHours,
    string ReviewState,
    bool CommercialAccessEnabled,
    string? AssignedReviewerId,
    string? AssignedReviewerName,
    DateTime? ReviewSubmittedAtUtc,
    DateTime? ReviewStartedAtUtc,
    DateTime? ReviewCompletedAtUtc,
    DateTime? RequestedChangesAtUtc,
    string? LastReviewDecision,
    VendorWorkspaceReviewSummaryDto ReviewSummary,
    IReadOnlyList<VendorWorkspaceReviewItemDto> ReviewItems,
    IReadOnlyList<VendorWorkspaceRequiredActionDto> RequiredActions,
    IReadOnlyList<VendorWorkspaceReviewAuditEntryDto> ReviewAuditEntries,
    int MissingDocumentsCount,
    bool CanSubmitForReview);

public record VendorWorkspaceReviewSummaryDto(
    int TotalItems,
    int ApprovedItems,
    int PendingVendorItems,
    int SubmittedItems,
    int ChangesRequestedItems,
    int WaivedItems);

public record VendorWorkspaceReviewItemDto(
    string Code,
    string Status,
    string? ReviewerId,
    string? ReviewerName,
    string? DecisionNote,
    DateTime? LastSubmittedAtUtc,
    DateTime? ReviewedAtUtc);

public record VendorWorkspaceRequiredActionDto(
    string Code,
    string Message);

public record VendorWorkspaceReviewAuditEntryDto(
    string Id,
    string Kind,
    string Tone,
    string Message,
    string RoleLabel,
    string AuthorName,
    DateTime CreatedAtUtc,
    string? ActorUserId,
    string? ReviewItemCode);
